# Nombre del workflow de prueba
name: Depuracion de Conexion y Rutas

# Se activa con cualquier push para probarlo fácilmente
on:
  push:
    branches:
      - main

jobs:
  debug-connection:
    runs-on: ubuntu-latest
    steps:
      - name: Conectar y Listar Directorio Home
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VM_IP_PUBLICA }}
          username: ${{ secrets.VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.VM_PORT }}
          script: |
            echo "✅ Conectado al servidor como $(whoami)."
            echo "📂 Listando contenido de /home/azureuser/ para verificar el nombre de la carpeta..."
            ls -la /home/azureuser/
